FROM python:3.12-slim-bookworm

WORKDIR /app
COPY pyproject.toml /app/pyproject.toml
COPY src /app/src
COPY scripts /app/scripts
COPY data /app/data

RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir .

EXPOSE 8501
CMD ["python", "scripts/start_prod.py"]
